// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VfkVisualization.Repositories;

#nullable disable

namespace VfkVisualization.Migrations
{
    [DbContext(typeof(VfkDataReadWriteContext))]
    [Migration("20250902210428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("VfkVisualization.Repositories.VfkDataExport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.HasKey("Id");

                    b.ToTable("vfk_export", (string)null);
                });

            modelBuilder.Entity("VfkVisualization.Repositories.VfkDataExportPrice", b =>
                {
                    b.Property<string>("ExportId")
                        .HasColumnType("TEXT")
                        .HasColumnName("export_id");

                    b.Property<long>("TelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tel_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CenaNabidkova")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cena_nabidkova");

                    b.Property<string>("Poznamka")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("poznamka");

                    b.HasKey("ExportId", "TelId", "CreatedAtUtc");

                    b.ToTable("vfk_export_price", (string)null);
                });

            modelBuilder.Entity("VfkVisualization.Repositories.VfkDataSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActiveExportId")
                        .HasColumnType("TEXT")
                        .HasColumnName("active_export_id");

                    b.Property<int?>("ActiveKatuzeKod")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_katuze_kod");

                    b.Property<string>("ActiveKatuzeName")
                        .HasColumnType("TEXT")
                        .HasColumnName("active_katuze_name");

                    b.HasKey("Id");

                    b.HasIndex("ActiveExportId")
                        .IsUnique();

                    b.ToTable("vfk_session", (string)null);
                });

            modelBuilder.Entity("VfkVisualization.Repositories.VfkDataExportPrice", b =>
                {
                    b.HasOne("VfkVisualization.Repositories.VfkDataExport", "Export")
                        .WithMany("Prices")
                        .HasForeignKey("ExportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Export");
                });

            modelBuilder.Entity("VfkVisualization.Repositories.VfkDataSession", b =>
                {
                    b.HasOne("VfkVisualization.Repositories.VfkDataExport", "ActiveExport")
                        .WithOne("Session")
                        .HasForeignKey("VfkVisualization.Repositories.VfkDataSession", "ActiveExportId");

                    b.Navigation("ActiveExport");
                });

            modelBuilder.Entity("VfkVisualization.Repositories.VfkDataExport", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Session");
                });
#pragma warning restore 612, 618
        }
    }
}
