// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VfkVisualization.Repositories;

#nullable disable

namespace VfkVisualization.Migrations
{
    [DbContext(typeof(VfkDataReadWriteContext))]
    [Migration("20250901223433_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("VfkVisualization.Repositories.VfkDataExport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.HasKey("Id");

                    b.ToTable("vfk_export", (string)null);
                });

            modelBuilder.Entity("VfkVisualization.Repositories.VfkDataExportPrice", b =>
                {
                    b.Property<string>("ExportId")
                        .HasColumnType("TEXT")
                        .HasColumnName("export_id");

                    b.Property<long>("TelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tel_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CenaNabidkova")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cena_nabidkova");

                    b.Property<string>("Poznamka")
                        .HasColumnType("TEXT")
                        .HasColumnName("poznamka");

                    b.HasKey("ExportId", "TelId", "CreatedAtUtc");

                    b.ToTable("vfk_export_price", (string)null);
                });

            modelBuilder.Entity("VfkVisualization.Repositories.VfkDataExportPrice", b =>
                {
                    b.HasOne("VfkVisualization.Repositories.VfkDataExport", "Export")
                        .WithMany("Prices")
                        .HasForeignKey("ExportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Export");
                });

            modelBuilder.Entity("VfkVisualization.Repositories.VfkDataExport", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
